### ISSUE TITLE
Changing the resolution of both Read and PWM Write to 12 for Due

### ISSUE THREAD

**Issue by EhsanMasoumi** [firmata/protocol#122]
Hi, I am wondering can you please help me to increase the resolution on Due to 12 instead of 10? 
I added the 2 lines to Ardunio Setup() function to do that and also changed the line representing 1023 and 255 counts in the Firmata code. is it correct or I should change other places too?

Thanks a lot

**Comment by pgrawehr** [comment]
That could work. But this question should go to https://github.com/firmata/ConfigurableFirmata. The Due is not officially supported by other implementations yet.
