### ISSUE TITLE
Found 2 Windows Firmata client libraries

### ISSUE THREAD

**Issue by human890209** [firmata/protocol#137]
https://github.com/ms-iot/remote-wiring

https://docs.microsoft.com/en-us/dotnet/api/iot.device.arduino?view=iot-dotnet-1.5

**Comment by pgrawehr** [comment]
Hi. The later one is already mentioned (under .NET), while the first one is no longer active as far as I know.

**Comment by human890209** [comment]
@pgrawehr Thanks.
