### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [firmata/protocol#142]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by pgrawehr** [comment]
Hi @codehangen 

Sorry for not seeing this. The project is active, but not so much _this_ repo.

This is only for protocol changes. The implementation that is being worked on (when needed) is ConfigurableFirmata. Do you have any particular change requirement or suggestion?

**Comment by pgrawehr** [comment]
@codehangen that's cool. You can just open a pull request. Ping me if you need help or if I don't do a review within a few days.
