### ISSUE TITLE
Digital write pin alongside of digital message port Proposal

### ISSUE THREAD

**Issue by jacobrosenthal** [firmata/protocol#3]
Wrote this out here as a wiki proposal, posted it to the devel list in Nov as well, but I'd like to get some conversation here where this might be more possible:

With the current digital message port, the host needs to reset or query pin state, then keep state in sync.

However with new implementations, like my BLE implementation, I dont want to force a reset on connect as BLE connects and disconnects possibly often. Instead Id have to do ~29 pin state queries to build an internal data structure, but thats hugely wasteful on an RF connection!

It also seems odd, anyway, to keep state which could get out of sync, when the board is already keeping state-- It can read its register settings any time!

I understand why the digitalmessage port was implemented like it was, it is clever to send 8 pins for 3 bytes. But in this scenario it can be equally or more efficient to send 4 bytes for 1 pin if it means we dodge ~29 pin state queries and config writes.
It seems like its time to have a digital message pin command in addition to the digitalMessagePort which could just move a single pin when state is unknown, or when you don't want to hold state in the host program.

We would have use up a sysex command
```
/* set digital pin
 * 0  START_SYSEX (0xF0)
 * 1  digital write pin (0x??)
 * 2  high/low (0x01)
 * 3  END_SYSEX (0xF7) (MIDI End of SysEx - EOX)
 */
```
 Another option actually, is to put optional on digital message port

```
/* two byte digital data format, second nibble of byte 0 gives the port number (e.g. 0x92 is the third port, port 2)
 * 0  digital data, 0x90-0x9F, (MIDI NoteOn, but different data format)
 * 1  digital pins 0-6 bitmask port values
 * 2  digital pin 7 bitmask port values
 * 3  digital pins 0-6 bitmask pins you want to effect
 * 4  digital pin 7 bitmask pins you want to effect
 */
```

http://firmata.org/wiki/Proposals#Digital_write_pin_alongside_of_digital_message_port

http://sourceforge.net/mailarchive/forum.php?thread_name=1384757311.2919.16.camel%40norbert-ThinkPad-X61s&forum_name=firmata-devel

**Comment by soundanalogous** [comment]
This feature is now available: The protocol is described here (see `set digital pin value`): https://github.com/firmata/protocol/blob/master/protocol.md#message-types. And an initial implementation for Arduino is available in this branch: https://github.com/firmata/arduino/tree/set-pin-value.
