### ISSUE TITLE
Documentation of protocol versions > 2.4?

### ISSUE THREAD

**Issue by finson** [firmata/protocol#37]
Are there protocol.md files for Firmata Protocol versions greater than 2.4?

**Comment by soundanalogous** [comment]
v2.4 is the current version

**Comment by finson** [comment]
Right, that's my question. I was hoping to find a protocol.md document that describes all features that are settled parts of the protocol as of a particular version so that if I write a client library I can specify that it conforms to a particular version as documented by protocol-2.x.md.  The current protocol.md document says it defines v 2.4, but it includes the v 2.5 single digital pin feature added in April.

**Comment by soundanalogous** [comment]
I need to document this, but any markdown file not prepended by "-proposal" is current. You are correct though in that determining the version is currently confusing. I should have been using tags and will going froward from 2.5. Also I added single digital pin prematurely. Should have kept it beta I added serial.

**Comment by finson** [comment]
Thx.
