### ISSUE TITLE
SAMPLEING_INTERVAL

### ISSUE THREAD

**Issue by zfields** [firmata/protocol#82]
SAMPLING_INTERVAL?

**Comment by soundanalogous** [comment]
yeah I assume you found a type somewhere. should be fixed

**Comment by zfields** [comment]
I have only seen it on the `protocol.md`, but I wanted to raise it here in case it has percolated to someplace I am not privy to.

**Comment by soundanalogous** [comment]
only other place it's mentioned is in feature-registry.md and it's spelled correctly there.
